#!/usr/bin/env node
// kb/regenerate.mjs — regenerate the COLD PATH digest (dev-docs/review-rules.md)
// from the GRADUATED lessons in the store. This file is @-imported by CLAUDE.md, so
// it is loaded into every agent's context. NEVER hand-edit it — edit the store and
// re-run this script (graduate.mjs does so automatically).
//
// Usage: node scripts/kb/regenerate.mjs

import { writeFileSync } from 'node:fs';
import { readStore, RULES_MD_PATH, CATEGORIES, bySeverityThenOccurrence } from './lib.mjs';

function main() {
  const graduated = readStore().filter((l) => l.status === 'graduated');

  const out = [];
  out.push('# Review Rules — graduated lessons (auto-generated)');
  out.push('');
  out.push(
    '> Generated by `scripts/kb/regenerate.mjs` from `dev-cycle-analytics/review-lessons.jsonl`.'
  );
  out.push(
    '> Do not edit by hand. These are recurring code-review findings that recurred often'
  );
  out.push(
    '> enough to graduate into always-loaded project rules. Honor them when writing code.'
  );
  out.push('');

  if (graduated.length === 0) {
    out.push('_No lessons have graduated yet. Active lessons live in the KB store and are');
    out.push('injected into the implementer at dev-cycle Phase 3 instead._');
    writeFileSync(RULES_MD_PATH, out.join('\n') + '\n', 'utf8');
    console.log(`regenerated ${RULES_MD_PATH}: 0 graduated lessons.`);
    return;
  }

  const present = CATEGORIES.filter((c) => graduated.some((l) => l.category === c));
  const extra = [...new Set(graduated.map((l) => l.category))].filter((c) => !present.includes(c));
  for (const cat of [...present, ...extra]) {
    const group = graduated.filter((l) => l.category === cat).sort(bySeverityThenOccurrence);
    if (group.length === 0) continue;
    out.push(`## ${cat}`);
    out.push('');
    for (const l of group) {
      out.push(`- **${l.title}.** ${l.rule}`);
      if (l.rationale) out.push(`  - _Why:_ ${l.rationale}`);
    }
    out.push('');
  }

  writeFileSync(RULES_MD_PATH, out.join('\n').trimEnd() + '\n', 'utf8');
  console.log(`regenerated ${RULES_MD_PATH}: ${graduated.length} graduated lesson(s).`);
}

main();
