CREATE TABLE weekly_aggregates (
    id TEXT PRIMARY KEY,
    developer_id TEXT NOT NULL REFERENCES developers(id),
    week_start TEXT NOT NULL,
    team TEXT NOT NULL,
    active_days INTEGER DEFAULT 0,
    total_interactions INTEGER DEFAULT 0,
    total_acceptances INTEGER DEFAULT 0,
    avg_acceptance_rate REAL,
    tools_used TEXT,
    estimated_total_cost REAL,
    total_commits INTEGER DEFAULT 0,
    total_lines_added INTEGER DEFAULT 0,
    total_prs_merged INTEGER DEFAULT 0,
    avg_code_churn REAL,
    avg_ai_signature_score REAL,
    subscription_cost REAL,
    cost_per_pr REAL,
    is_active INTEGER DEFAULT 0,
    data_quality TEXT,
    computed_at TEXT NOT NULL,
    UNIQUE(developer_id, week_start)
);

CREATE TABLE monthly_aggregates (
    id TEXT PRIMARY KEY,
    developer_id TEXT NOT NULL REFERENCES developers(id),
    month TEXT NOT NULL,
    team TEXT NOT NULL,
    active_days INTEGER DEFAULT 0,
    active_weeks INTEGER DEFAULT 0,
    total_interactions INTEGER DEFAULT 0,
    avg_acceptance_rate REAL,
    tools_used TEXT,
    estimated_total_cost REAL,
    total_commits INTEGER DEFAULT 0,
    total_lines_added INTEGER DEFAULT 0,
    total_prs_merged INTEGER DEFAULT 0,
    avg_code_churn REAL,
    avg_ai_signature_score REAL,
    subscription_cost REAL,
    cost_per_pr REAL,
    is_active INTEGER DEFAULT 0,
    data_quality TEXT,
    interaction_delta_pct REAL,
    acceptance_rate_delta REAL,
    commit_velocity_delta_pct REAL,
    churn_rate_delta REAL,
    computed_at TEXT NOT NULL,
    UNIQUE(developer_id, month)
);

CREATE TABLE quarterly_aggregates (
    id TEXT PRIMARY KEY,
    team TEXT NOT NULL,
    quarter TEXT NOT NULL,
    developer_count INTEGER DEFAULT 0,
    active_developer_count INTEGER DEFAULT 0,
    utilization_rate REAL,
    total_subscription_cost REAL,
    total_estimated_api_cost REAL,
    unused_seat_count INTEGER DEFAULT 0,
    wasted_spend REAL,
    avg_acceptance_rate REAL,
    avg_code_churn REAL,
    total_prs_merged INTEGER DEFAULT 0,
    cost_per_pr REAL,
    ai_maturity_score REAL,
    utilization_rate_delta REAL,
    maturity_score_delta REAL,
    computed_at TEXT NOT NULL,
    UNIQUE(team, quarter)
);
