-- Task 5.7 (#128): Session Retrospective — the deep async coaching layer (Pillar 3).
--
-- A retrospective is the OUTPUT of an AI coach reviewing one of a developer's
-- captured sessions: a personalized, within-developer narrative (what worked,
-- where prompts were underspecified, where loops burned time) plus structured
-- highlights. It is generated by TRANSIENTLY decrypting the session's ciphertext
-- in memory with the developer's key, running analysis, and storing ONLY the
-- analysis output here. The raw prompts/responses are NEVER stored in this table
-- (or anywhere readable) — the plaintext exists only in memory for the duration
-- of the analysis and is then discarded.
--
-- Privacy model (identical posture to prompt_captures / loop_events): every row
-- is scoped to its developer_id and is private to that developer. The generate
-- and read routes both derive developer_id from the session, never from input,
-- so one developer can never reach another's retrospective, and there is NO
-- manager/aggregate path over this table — ever.
--
-- analysis_location records WHERE the analysis ran so the developer can see it:
--   local — a local model (e.g. Ollama) on org infrastructure; the DEFAULT, and
--           the only path where raw prompts never leave org infra.
--   cloud — a cloud model; reached ONLY when the org permits cloud analysis AND
--           the developer consciously opted in (opt-in #2). Recorded so the
--           developer always knows their prompts were sent externally for a run.
CREATE TABLE retrospectives (
    id TEXT PRIMARY KEY,
    -- CASCADE: a developer's private retrospectives should die with the developer
    -- record (no orphaned coaching narratives), matching how prompt_captures and
    -- every sibling FK declares its delete intent.
    developer_id TEXT NOT NULL REFERENCES developers(id) ON DELETE CASCADE,
    -- The captured session this retrospective reviewed (the session_id that groups
    -- prompt_captures rows). Not a FK: a session_id intentionally groups MANY
    -- capture rows and is not unique, so it can't be a foreign key target.
    session_id TEXT NOT NULL,
    generated_at TEXT NOT NULL,            -- when the retrospective was produced (UTC ISO)
    analysis_model TEXT NOT NULL,          -- local model name | cloud model name
    -- Where analysis ran. CHECK locks it to the two known locations so a corrupt/
    -- unknown value can't masquerade as one the UI trusts.
    analysis_location TEXT NOT NULL CHECK (analysis_location IN ('local', 'cloud')),
    retrospective_text TEXT NOT NULL,      -- the coaching narrative (private to dev)
    highlights TEXT,                       -- JSON: { worked: string[], improve: string[] }
    created_at TEXT NOT NULL               -- when the server stored the row (UTC ISO)
);

-- The developer's own listing is "my retrospectives, newest first" and "this
-- session's retrospectives" — both keyed on developer_id, so index it alongside
-- generated_at and session_id for the private read paths.
CREATE INDEX idx_retrospectives_dev_generated ON retrospectives(developer_id, generated_at);
CREATE INDEX idx_retrospectives_dev_session ON retrospectives(developer_id, session_id);
