-- Task 6.5 (#174): Private "How Could This Be Better" Tool — the SEPARATE,
-- purpose-built counterpart to the deliberately-excluded showcase critique.
--
-- A developer runs this on their OWN captured conversations for self-directed
-- improvement. An improvement_review is the OUTPUT of analysing one conversation:
-- a constructive, within-developer narrative plus structured, specific
-- suggestions. As with retrospectives, it is generated by TRANSIENTLY decrypting
-- the session's ciphertext in memory with the developer's key, running analysis,
-- and storing ONLY the analysis output here. The raw prompts/responses are NEVER
-- stored in this table — the plaintext exists only in memory for the duration of
-- the analysis and is then discarded. (On the LOCAL default path the plaintext
-- never leaves org infra at all; a deployment-provided CLOUD analyser's narrative
-- output is persisted verbatim, so that text is only as private as the cloud model
-- the developer opted into — which is why cloud requires the Phase 5 double-opt-in.)
--
-- Privacy model (identical posture to retrospectives / prompt_captures): every
-- row is scoped to its developer_id and is private to that developer. The
-- generate and read routes both derive developer_id from the session, never from
-- input, so one developer can never reach another's review. There is NO publish
-- path and NO manager/aggregate path over this table — ever. This is where the
-- sharp, private feedback lives; the public showcase carries none of it.
--
-- analysis_location records WHERE the analysis ran so the developer can see it:
--   local — a local model on org infrastructure; the DEFAULT, and the only path
--           where raw prompts never leave org infra.
--   cloud — a cloud model; reached ONLY under the Phase 5 double-opt-in (org
--           permits cloud analysis AND the developer opted in). Recorded so the
--           developer always knows their prompts were sent externally for a run.
CREATE TABLE improvement_reviews (
    id TEXT PRIMARY KEY,
    -- CASCADE: a developer's private reviews should die with the developer record
    -- (no orphaned reviews), matching how retrospectives and every sibling FK
    -- declares its delete intent.
    developer_id TEXT NOT NULL REFERENCES developers(id) ON DELETE CASCADE,
    -- The captured conversation this review analysed (the session_id that groups
    -- prompt_captures rows). Not a FK: a session_id intentionally groups MANY
    -- capture rows and is not unique, so it can't be a foreign key target.
    session_id TEXT NOT NULL,
    generated_at TEXT NOT NULL,            -- when the review was produced (UTC ISO)
    analysis_model TEXT NOT NULL,          -- local model name | cloud model name
    -- Where analysis ran. CHECK locks it to the two known locations so a corrupt/
    -- unknown value can't masquerade as one the UI trusts.
    analysis_location TEXT NOT NULL CHECK (analysis_location IN ('local', 'cloud')),
    review_text TEXT NOT NULL,             -- the constructive narrative (private to dev)
    -- JSON: ImprovementSuggestion[] — [{ category, suggestion }]. Categories are
    -- validated against an allowlist at the write boundary AND on read.
    suggestions TEXT NOT NULL,
    -- Provenance: how many capture rows the review was derived from. Counts only —
    -- never the prompts themselves.
    analyzed_capture_count INTEGER NOT NULL,
    created_at TEXT NOT NULL               -- when the server stored the row (UTC ISO)
);

-- The developer's own listing is "my reviews, newest first" and "this
-- conversation's reviews" — both keyed on developer_id, so index it alongside
-- generated_at and session_id for the private read paths.
CREATE INDEX idx_improvement_reviews_dev_generated ON improvement_reviews(developer_id, generated_at);
CREATE INDEX idx_improvement_reviews_dev_session ON improvement_reviews(developer_id, session_id);
